<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="huoping-47" failures="0" tests="17" name="com.huoping.test.TestUsers" time="0.329" errors="1" timestamp="2022-07-10T15:00:46 CST" skipped="0">
  <testcase classname="com.huoping.test.TestUsers" name="testgetCondition" time="0.004"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="testGetByMap" time="0.004"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="testInsertList" time="0.009"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="getAllMap" time="0.003"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="getByName" time="0.005"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="createUUID" time="0.000"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="testSelect" time="0.004"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="testInsert" time="0.008">
    <error message="
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;insert
        into users(username, birthday, sex, address)
        values
     &#039; at line 2
### The error may exist in com/huoping/mapper/UserMapper.xml
### The error may involve com.huoping.mapper.UserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: select last_insert_id()             insert         into users(username, birthday, sex, address)         values             (?, ?, ?, ?)
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;insert
        into users(username, birthday, sex, address)
        values
     &#039; at line 2" type="org.apache.ibatis.exceptions.PersistenceException">
      <![CDATA[org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'insert
        into users(username, birthday, sex, address)
        values
     ' at line 2
### The error may exist in com/huoping/mapper/UserMapper.xml
### The error may involve com.huoping.mapper.UserMapper.insert-Inline
### The error occurred while setting parameters
### SQL: select last_insert_id()             insert         into users(username, birthday, sex, address)         values             (?, ?, ?, ?)
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'insert
        into users(username, birthday, sex, address)
        values
     ' at line 2
at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
at com.sun.proxy.$Proxy8.insert(Unknown Source)
at com.huoping.test.TestUsers.testInsert(TestUsers.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'insert
        into users(username, birthday, sex, address)
        values
     ' at line 2
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:372)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
at com.sun.proxy.$Proxy10.execute(Unknown Source)
at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
... 43 more
]]>
    </error>
  </testcase> <!-- testInsert -->
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="testUsers" time="0.005"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="testUpdateSet" time="0.004"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="getId" time="0.002"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="testDelete" time="0.002"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="TestGetById" time="0.024"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="TestGetByUserMap" time="0.002"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="TestDeleteById" time="0.244"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="getUserDate" time="0.005"/>
  <system-out/>
  <testcase classname="com.huoping.test.TestUsers" name="testUpdate" time="0.004"/>
  <system-out/>
</testsuite> <!-- com.huoping.test.TestUsers -->
